# Currently there's no doc tests nor code coverage on wasm.

language: rust


# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo


# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


addons:
  firefox: latest
  chrome : stable


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      script:
        - bash ci/server.bash
        - bash ci/tests.bash


    - name: linux nightly rust
      os  : linux
      rust: nightly

      script:
        - bash ci/server.bash
        - bash ci/tests.bash
        - bash ci/docs.bash


    - name: osx stable rust
      os  : osx
      rust: stable

      script:
        - bash ci/server.bash
        - bash ci/tests.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      script:
        - bash ci/server.bash
        - bash ci/tests.bash
